FROM python:3.11.1-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

EXPOSE 8000

COPY ./requirements.txt ./
RUN pip install --upgrade pip --no-cache-dir & \
    pip install -r requirements.txt --no-cache-dir

COPY app /app/

WORKDIR /app

CMD ["uvicorn", "main:app", "--workers", "4", "--host", "0.0.0.0", "--port", "8000"]
